import { Vector2 } from "three";
interface IDragState {
    data: any;
    actionTarget: "" | "addToScene";
    endArea: "" | "Drawing" | "Scene";
    endPosition: Vector2;
}
/**
 * 拖拽相关
 */
export declare const useDragStore: import("pinia").StoreDefinition<"drag", IDragState, {
    getData: (state: {
        data: any;
        actionTarget: "" | "addToScene";
        endArea: "" | "Drawing" | "Scene";
        endPosition: {
            x: number;
            y: number;
            width: number;
            height: number;
            readonly isVector2: true;
            set: (x: number, y: number) => Vector2;
            setScalar: (scalar: number) => Vector2;
            setX: (x: number) => Vector2;
            setY: (y: number) => Vector2;
            setComponent: (index: number, value: number) => Vector2;
            getComponent: (index: number) => number;
            clone: () => Vector2;
            copy: (v: import("three").Vector2Like) => Vector2;
            add: (v: import("three").Vector2Like) => Vector2;
            addScalar: (s: number) => Vector2;
            addVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            addScaledVector: (v: import("three").Vector2Like, s: number) => Vector2;
            sub: (v: import("three").Vector2Like) => Vector2;
            subScalar: (s: number) => Vector2;
            subVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            multiply: (v: import("three").Vector2Like) => Vector2;
            multiplyScalar: (scalar: number) => Vector2;
            divide: (v: import("three").Vector2Like) => Vector2;
            divideScalar: (s: number) => Vector2;
            applyMatrix3: (m: import("three").Matrix3) => Vector2;
            min: (v: import("three").Vector2Like) => Vector2;
            max: (v: import("three").Vector2Like) => Vector2;
            clamp: (min: import("three").Vector2Like, max: import("three").Vector2Like) => Vector2;
            clampScalar: (min: number, max: number) => Vector2;
            clampLength: (min: number, max: number) => Vector2;
            floor: () => Vector2;
            ceil: () => Vector2;
            round: () => Vector2;
            roundToZero: () => Vector2;
            negate: () => Vector2;
            dot: (v: import("three").Vector2Like) => number;
            cross: (v: import("three").Vector2Like) => number;
            lengthSq: () => number;
            length: () => number;
            manhattanLength: () => number;
            normalize: () => Vector2;
            angle: () => number;
            angleTo: (v: Vector2) => number;
            distanceTo: (v: import("three").Vector2Like) => number;
            distanceToSquared: (v: import("three").Vector2Like) => number;
            manhattanDistanceTo: (v: import("three").Vector2Like) => number;
            setLength: (length: number) => Vector2;
            lerp: (v: import("three").Vector2Like, alpha: number) => Vector2;
            lerpVectors: (v1: import("three").Vector2Like, v2: import("three").Vector2Like, alpha: number) => Vector2;
            equals: (v: import("three").Vector2Like) => boolean;
            fromArray: (array: number[] | ArrayLike<number>, offset?: number) => Vector2;
            toArray: {
                (array?: number[], offset?: number): number[];
                (array?: import("three").Vector2Tuple, offset?: 0): import("three").Vector2Tuple;
                (array: ArrayLike<number>, offset?: number): ArrayLike<number>;
            };
            fromBufferAttribute: (attribute: import("three").BufferAttribute, index: number) => Vector2;
            rotateAround: (center: import("three").Vector2Like, angle: number) => Vector2;
            random: () => Vector2;
            [Symbol.iterator]: () => Iterator<number>;
        };
    } & import("pinia").PiniaCustomStateProperties<IDragState>) => any;
    getActionTarget: (state: {
        data: any;
        actionTarget: "" | "addToScene";
        endArea: "" | "Drawing" | "Scene";
        endPosition: {
            x: number;
            y: number;
            width: number;
            height: number;
            readonly isVector2: true;
            set: (x: number, y: number) => Vector2;
            setScalar: (scalar: number) => Vector2;
            setX: (x: number) => Vector2;
            setY: (y: number) => Vector2;
            setComponent: (index: number, value: number) => Vector2;
            getComponent: (index: number) => number;
            clone: () => Vector2;
            copy: (v: import("three").Vector2Like) => Vector2;
            add: (v: import("three").Vector2Like) => Vector2;
            addScalar: (s: number) => Vector2;
            addVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            addScaledVector: (v: import("three").Vector2Like, s: number) => Vector2;
            sub: (v: import("three").Vector2Like) => Vector2;
            subScalar: (s: number) => Vector2;
            subVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            multiply: (v: import("three").Vector2Like) => Vector2;
            multiplyScalar: (scalar: number) => Vector2;
            divide: (v: import("three").Vector2Like) => Vector2;
            divideScalar: (s: number) => Vector2;
            applyMatrix3: (m: import("three").Matrix3) => Vector2;
            min: (v: import("three").Vector2Like) => Vector2;
            max: (v: import("three").Vector2Like) => Vector2;
            clamp: (min: import("three").Vector2Like, max: import("three").Vector2Like) => Vector2;
            clampScalar: (min: number, max: number) => Vector2;
            clampLength: (min: number, max: number) => Vector2;
            floor: () => Vector2;
            ceil: () => Vector2;
            round: () => Vector2;
            roundToZero: () => Vector2;
            negate: () => Vector2;
            dot: (v: import("three").Vector2Like) => number;
            cross: (v: import("three").Vector2Like) => number;
            lengthSq: () => number;
            length: () => number;
            manhattanLength: () => number;
            normalize: () => Vector2;
            angle: () => number;
            angleTo: (v: Vector2) => number;
            distanceTo: (v: import("three").Vector2Like) => number;
            distanceToSquared: (v: import("three").Vector2Like) => number;
            manhattanDistanceTo: (v: import("three").Vector2Like) => number;
            setLength: (length: number) => Vector2;
            lerp: (v: import("three").Vector2Like, alpha: number) => Vector2;
            lerpVectors: (v1: import("three").Vector2Like, v2: import("three").Vector2Like, alpha: number) => Vector2;
            equals: (v: import("three").Vector2Like) => boolean;
            fromArray: (array: number[] | ArrayLike<number>, offset?: number) => Vector2;
            toArray: {
                (array?: number[], offset?: number): number[];
                (array?: import("three").Vector2Tuple, offset?: 0): import("three").Vector2Tuple;
                (array: ArrayLike<number>, offset?: number): ArrayLike<number>;
            };
            fromBufferAttribute: (attribute: import("three").BufferAttribute, index: number) => Vector2;
            rotateAround: (center: import("three").Vector2Like, angle: number) => Vector2;
            random: () => Vector2;
            [Symbol.iterator]: () => Iterator<number>;
        };
    } & import("pinia").PiniaCustomStateProperties<IDragState>) => "" | "addToScene";
}, {
    setData(data: any): void;
    setActionTarget(actionTarget: any): void;
    setEndArea(area: any): void;
}>;
export declare function useDragStoreWithOut(): import("pinia").Store<"drag", IDragState, {
    getData: (state: {
        data: any;
        actionTarget: "" | "addToScene";
        endArea: "" | "Drawing" | "Scene";
        endPosition: {
            x: number;
            y: number;
            width: number;
            height: number;
            readonly isVector2: true;
            set: (x: number, y: number) => Vector2;
            setScalar: (scalar: number) => Vector2;
            setX: (x: number) => Vector2;
            setY: (y: number) => Vector2;
            setComponent: (index: number, value: number) => Vector2;
            getComponent: (index: number) => number;
            clone: () => Vector2;
            copy: (v: import("three").Vector2Like) => Vector2;
            add: (v: import("three").Vector2Like) => Vector2;
            addScalar: (s: number) => Vector2;
            addVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            addScaledVector: (v: import("three").Vector2Like, s: number) => Vector2;
            sub: (v: import("three").Vector2Like) => Vector2;
            subScalar: (s: number) => Vector2;
            subVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            multiply: (v: import("three").Vector2Like) => Vector2;
            multiplyScalar: (scalar: number) => Vector2;
            divide: (v: import("three").Vector2Like) => Vector2;
            divideScalar: (s: number) => Vector2;
            applyMatrix3: (m: import("three").Matrix3) => Vector2;
            min: (v: import("three").Vector2Like) => Vector2;
            max: (v: import("three").Vector2Like) => Vector2;
            clamp: (min: import("three").Vector2Like, max: import("three").Vector2Like) => Vector2;
            clampScalar: (min: number, max: number) => Vector2;
            clampLength: (min: number, max: number) => Vector2;
            floor: () => Vector2;
            ceil: () => Vector2;
            round: () => Vector2;
            roundToZero: () => Vector2;
            negate: () => Vector2;
            dot: (v: import("three").Vector2Like) => number;
            cross: (v: import("three").Vector2Like) => number;
            lengthSq: () => number;
            length: () => number;
            manhattanLength: () => number;
            normalize: () => Vector2;
            angle: () => number;
            angleTo: (v: Vector2) => number;
            distanceTo: (v: import("three").Vector2Like) => number;
            distanceToSquared: (v: import("three").Vector2Like) => number;
            manhattanDistanceTo: (v: import("three").Vector2Like) => number;
            setLength: (length: number) => Vector2;
            lerp: (v: import("three").Vector2Like, alpha: number) => Vector2;
            lerpVectors: (v1: import("three").Vector2Like, v2: import("three").Vector2Like, alpha: number) => Vector2;
            equals: (v: import("three").Vector2Like) => boolean;
            fromArray: (array: number[] | ArrayLike<number>, offset?: number) => Vector2;
            toArray: {
                (array?: number[], offset?: number): number[];
                (array?: import("three").Vector2Tuple, offset?: 0): import("three").Vector2Tuple;
                (array: ArrayLike<number>, offset?: number): ArrayLike<number>;
            };
            fromBufferAttribute: (attribute: import("three").BufferAttribute, index: number) => Vector2;
            rotateAround: (center: import("three").Vector2Like, angle: number) => Vector2;
            random: () => Vector2;
            [Symbol.iterator]: () => Iterator<number>;
        };
    } & import("pinia").PiniaCustomStateProperties<IDragState>) => any;
    getActionTarget: (state: {
        data: any;
        actionTarget: "" | "addToScene";
        endArea: "" | "Drawing" | "Scene";
        endPosition: {
            x: number;
            y: number;
            width: number;
            height: number;
            readonly isVector2: true;
            set: (x: number, y: number) => Vector2;
            setScalar: (scalar: number) => Vector2;
            setX: (x: number) => Vector2;
            setY: (y: number) => Vector2;
            setComponent: (index: number, value: number) => Vector2;
            getComponent: (index: number) => number;
            clone: () => Vector2;
            copy: (v: import("three").Vector2Like) => Vector2;
            add: (v: import("three").Vector2Like) => Vector2;
            addScalar: (s: number) => Vector2;
            addVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            addScaledVector: (v: import("three").Vector2Like, s: number) => Vector2;
            sub: (v: import("three").Vector2Like) => Vector2;
            subScalar: (s: number) => Vector2;
            subVectors: (a: import("three").Vector2Like, b: import("three").Vector2Like) => Vector2;
            multiply: (v: import("three").Vector2Like) => Vector2;
            multiplyScalar: (scalar: number) => Vector2;
            divide: (v: import("three").Vector2Like) => Vector2;
            divideScalar: (s: number) => Vector2;
            applyMatrix3: (m: import("three").Matrix3) => Vector2;
            min: (v: import("three").Vector2Like) => Vector2;
            max: (v: import("three").Vector2Like) => Vector2;
            clamp: (min: import("three").Vector2Like, max: import("three").Vector2Like) => Vector2;
            clampScalar: (min: number, max: number) => Vector2;
            clampLength: (min: number, max: number) => Vector2;
            floor: () => Vector2;
            ceil: () => Vector2;
            round: () => Vector2;
            roundToZero: () => Vector2;
            negate: () => Vector2;
            dot: (v: import("three").Vector2Like) => number;
            cross: (v: import("three").Vector2Like) => number;
            lengthSq: () => number;
            length: () => number;
            manhattanLength: () => number;
            normalize: () => Vector2;
            angle: () => number;
            angleTo: (v: Vector2) => number;
            distanceTo: (v: import("three").Vector2Like) => number;
            distanceToSquared: (v: import("three").Vector2Like) => number;
            manhattanDistanceTo: (v: import("three").Vector2Like) => number;
            setLength: (length: number) => Vector2;
            lerp: (v: import("three").Vector2Like, alpha: number) => Vector2;
            lerpVectors: (v1: import("three").Vector2Like, v2: import("three").Vector2Like, alpha: number) => Vector2;
            equals: (v: import("three").Vector2Like) => boolean;
            fromArray: (array: number[] | ArrayLike<number>, offset?: number) => Vector2;
            toArray: {
                (array?: number[], offset?: number): number[];
                (array?: import("three").Vector2Tuple, offset?: 0): import("three").Vector2Tuple;
                (array: ArrayLike<number>, offset?: number): ArrayLike<number>;
            };
            fromBufferAttribute: (attribute: import("three").BufferAttribute, index: number) => Vector2;
            rotateAround: (center: import("three").Vector2Like, angle: number) => Vector2;
            random: () => Vector2;
            [Symbol.iterator]: () => Iterator<number>;
        };
    } & import("pinia").PiniaCustomStateProperties<IDragState>) => "" | "addToScene";
}, {
    setData(data: any): void;
    setActionTarget(actionTarget: any): void;
    setEndArea(area: any): void;
}>;
export {};
